debug: false

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=false
    registry: registry.stevem.io
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: uberamd/ublog-hugo
    tag: $$COMMIT
    file: Dockerfile
    insecure: false
