---
kind: pipeline
type: ssh
name: default

server:
  host: 10.7.100.199
  user: webapp
  password:
    from_secret: ssh_password

steps:
- name: initialize
  commands:
  - git submodule update --init
  - hugo version
  - ln -s /home/hebron/hugo_resources/production resources

- name: build
  commands:
  - hugo --gc -b https://www.stevem.io/

- name: deploy-files
  commands:
  - rsync -avz --delete public/ /var/www/html
